'''

                            Online Python Compiler.
                Code, Compile, Run and Debug python program online.
Write your code in this editor and press "Run" button to execute it.

'''

ranks = {
"Elaine_Kasimatis.f" : 1,
"Events_Calendars.f" : 0,
"Student_Organizations.f" : 0,
"Quantitative_Biology_and_Bioinformatics.f" : 1,
"Private_Tutoring.f" : 0,
"Economics.f" : 1,
"Biological_Systems_Engineering.f" : 1,
"UC_Davis_English_Department.f" : 0,
"Computer_Science.f" : 1,
"What_I_Wish_I_Knew...Before_Coming_to_UC_Davis_Entomology.f" : 1,
"Graduate_Groups.f" : 1,
"Evelyn_Silvia.f" : 1,
"Fiber_and_Polymer_Science.f" : 1,
"UCD_Honors_and_Prizes.f" : 0,
"document_translated.f" : 0,
"Statistics.f" : 2,
"University_Departments.f" : 1,
"ECE_Course_Reviews.f" : 1,
"Hydrology.f" : 0,
"MattHh.f" : 0,
"Candidate_Statements.f" : 0,
"Wildlife%2C_Fish%2C_and_Conservation_Biology.f" : 0,
"Mathematics.f" : 3,
"Math.f" : 1,
"TravisTaylor.f" : 0,
"Grad_Students.f" : 1,
"Davis_Graduate.f" : 0,
"The_Grad.f" : 0,
"EfremRensi.f" : 1,
"GRE.f" : 0,
"JulieB.f" : 0,
"Mentorships_for_Undergraduate_Research_in_Agriculture%2C_Letters%2C_and_Science.f" : 0,
"EOP.f" : 0,
"Wilfred.f" : 0,
"Planned_Education_Leave_Program.f" : 0,
"Agricultural_Chemistry.f" : 0,
"JillNi.f" : 0,
"DavidGeisler.f" : 0,
"ESLP.f" : 0,
"APILP.f" : 0,
"Bridge.f" : 0,
"UCDC.f" : 0,
"Pharmacology_and_Toxicology.f" : 0,
"Bridge_Outreach_and_Retention_Program.f" : 0,
"Elliott.f" : 0,
"Santani.f" : 0,
"JoshBurkart.f" : 0,
"Free_Munchies_at_Bars.f" : 0,
"SamSampson.f" : 1,
"UC_Davis_Wrestling.f" : 0,
"GradLink.f" : 0,
"1927.f" : 0,
"DanielHoang.f" : 0,
"Graduate_Academic_Achievement_and_Advocacy_Program.f" : 1,
"Society_for_Industrial_and_Applied_Mathematics.f" : 2,
"East_Asian_Languages_and_Cultures.f" : 0,
"30-40_Something_Grad_Students.f" : 0,
"Yeni.f" : 0,
"ErikStaab.f" : 0,
"JamesShearer.f" : 0,
"MichaelTehranian.f" : 0,
"Western_Institute_for_Food_Safety_and_Security.f" : 0,
"UC_Davis_Women%27s_Gymnastics.f" : 0,
"SIAM.f" : 0,
"Meals_on_Wheels.f" : 0,
"Mathematics_ArXiv_front.f" : 1,
"Kraig%21Kraft%21.f" : 0,
"MotokiWu.f" : 1,
"McNair_Scholars_Program.f" : 0,
"Agricultural_%26_Environmental_Chemistry_Graduate_Group.f" : 0,
"ThucNghiNguyen.f" : 0,
"1963.f" : 0,
"JudsonWickham.f" : 1,
"MichaelGoodell.f" : 0,
"JeyKottalam.f" : 0,
"ChristopherCondap.f" : 0,
"Kristi.f" : 0,
"UC_Davis_Academics.f" : 0,
"Graduate_Students.f" : 2,
"The_Graduate.f" : 1,
"Graduate_Record_Examinations.f" : 2,
"Educational_Opportunity_Program.f" : 2,
"Planned_Educational_Leave_Program.f" : 1,
"Education_For_Sustainable_Living_Program.f" : 0,
"Asian_Pacific_Islander_Leadership_Program.f" : 0,
"Quantitative_Biology_and_bioinformatics.f" : 1,
"Landscape_Architecture.f" : 0,
"University_of_California_Washington_Center_Program.f" : 2,
"Double_Aggie.f" : 0,
"Geography_Graduate_Group.f" : 0,
"Graduate_Student_Community_Service_Committee.f" : 0,
"CLIMB.f" : 2,
"Yolo_County_Probation_Work_Program.f" : 0,
"Graduate_Student_Social_Event_Calendar.f" : 1,
"UC_Davis_Colleges.f" : 0,
"Jewish_Studies.f" : 0,
"Biology_Undergraduate_Scholars_Program.f" : 0,
"SonnyMohammadzadeh.f" : 1,
"computer_science.f" : 2,
"economics.f" : 2,
"hydrology.f" : 1,
"mathematics.f" : 3,
"private_tutoring.f" : 0,
"statistics.f" : 3,
"student_organizations.f" : 0,
"MURALS_%28Mentorship_Program%29.f" : 0,
"February_1%2C_2007.f" : 0,
"Roommates_Wanted.f" : 0,
"Jonathan_Mitchell.f" : 0,
"Unqualified_Candidates_Scandal.f" : 0,
"5th_Street_Redesign.f" : 0,
"2007-2010_Archive.f" : 0,
"Getting_the_most_out_of_your_student_fees.f" : 0,
"Target_Debate.f" : 0,
"Fuzzy_Math.f" : 2,
"Calculus.f" : 3,
"Christopher_Tuffley.f" : 2,
"Lost_and_Found.f" : 0,
"Children%27s_Summer_Programs.f" : 1,
"Genetics.f" : 1,
"Memorable_Quotes.f" : 0,
"Teaching_Assistants.f" : 0,
"PatrickVisperas.f" : 0,
"Shadiness_Factor.f" : 0,
"SachinSalgaonkar.f" : 1,
"Linda_Katehi.f" : 0,
"PaulCernea.f" : 1,
"Davis_Math_Tutoring.f" : 2,
"math.f" : 0,
"Grad_students.f" : 1,

"Pladd.f" : 0,
"Calculus_Room.f" : 0,
"MSB.f" : 0,
"Tri_Delt.f" : 0,
"The_Gap.f" : 0,
"AmitSahoo.f" : 0,
"DavePoole.f" : 0,
"DavidPoole.f" : 0,
"David_Poole.f" : 0,
"Physics_and_Geology.f" : 0,
"Language_Learning_Center.f" : 0,
"Civil_Engineering.f" : 0,
"RoyWright.f" : 0,
"Biological_Sciences.f" : 0,
"Biology.f" : 0,
"Division_of_Biological_Sciences.f" : 0,
"AJThompson.f" : 0,
"SeatonTsai.f" : 0,
"Majors.f" : 2,
"WFCB.f" : 0,
"Minors.f" : 0,
"Environmental_Science_and_Management.f" : 0,
"EthanLeavy.f" : 0,
"Professor.f" : 0,
"GeorgeSuarez.f" : 0,
"FrankWu.f" : 0,
"Computer_Science_and_Engineering.f" : 0,
"ECS.f" : 0,
"matt%27s_courses.f" : 0,
"Weeder_Classes.f" : 0,
"LarinLucero.f" : 0,
"Apex_Computer_Services.f" : 0,
"Measures.f" : 0,
"NoraSandstedt.f" : 0,
"Millenniumchilddevelopmentcenter.f" : 0,
"UC_Davis_Chinese_Program.f" : 0,
"Staples.f" : 0,
"CSE.f" : 0,
"S.T.E.P..f" : 0,
"Undergrads.f" : 0,
"Undergraduates.f" : 0,
"Christian_%27Eight-Ball%27_Alvarez.f" : 0,
}

query1 = [
"Math.f",
"TravisTaylor.f",
"Davis_Graduate.f",
"Grad_Students.f",
"The_Grad.f",
"EfremRensi.f",
"GRE.f",
"JulieB.f",
"EOP.f",
"Mentorships_for_Undergraduate_Research_in_Agriculture%2C_Letters%2C_and_Science.f",
"Wilfred.f",
"Planned_Education_Leave_Program.f",
"Agricultural_Chemistry.f",
"JillNi.f",
"DavidGeisler.f",
"APILP.f",
"Bridge.f",
"ESLP.f",
"UCDC.f",
"Pharmacology_and_Toxicology.f",
"Bridge_Outreach_and_Retention_Program.f",
"Elaine_Kasimatis.f",
"Elliott.f",
"Santani.f",
"JoshBurkart.f",
"Free_Munchies_at_Bars.f",
"SamSampson.f",
"UC_Davis_Wrestling.f",
"GradLink.f",
"Evelyn_Silvia.f",
"1927.f",
"DanielHoang.f",
"Graduate_Academic_Achievement_and_Advocacy_Program.f",
"Society_for_Industrial_and_Applied_Mathematics.f",
"East_Asian_Languages_and_Cultures.f",
"30-40_Something_Grad_Students.f",
"Yeni.f",
"ErikStaab.f",
"JamesShearer.f",
"MichaelTehranian.f",
"UC_Davis_Women%27s_Gymnastics.f",
"Western_Institute_for_Food_Safety_and_Security.f",
"SIAM.f",
"Meals_on_Wheels.f",
"Mathematics_ArXiv_front.f",
"Kraig%21Kraft%21.f",
"MotokiWu.f",
"McNair_Scholars_Program.f",
"Agricultural_%26_Environmental_Chemistry_Graduate_Group.f",
"ThucNghiNguyen.f",
]

query2 = [
"Pladd.f",
"Mathematics.f",
"Calculus_Room.f",
"MSB.f",
"Tri_Delt.f",
"JillNi.f",
"The_Gap.f",
"AmitSahoo.f",
"DavePoole.f",
"DavidPoole.f",
"David_Poole.f",
"Math.f",
"Physics_and_Geology.f",
"Language_Learning_Center.f",
"Civil_Engineering.f",
"RoyWright.f",
"Biological_Sciences.f",
"Biology.f",
"Division_of_Biological_Sciences.f",
"AJThompson.f",
"SeatonTsai.f",
"Majors.f",
"WFCB.f",
"Minors.f",
"Quantitative_Biology_and_Bioinformatics.f",
"Environmental_Science_and_Management.f",
"EthanLeavy.f",
"Professor.f",
"JoshBurkart.f",
"GeorgeSuarez.f",
"FrankWu.f",
"Computer_Science_and_Engineering.f",
"ECS.f",
"Calculus.f",
"matt%27s_courses.f",
"Weeder_Classes.f",
"LarinLucero.f",
"TravisTaylor.f",
"Apex_Computer_Services.f",
"Measures.f",
"NoraSandstedt.f",
"Millenniumchilddevelopmentcenter.f",
"UC_Davis_Chinese_Program.f",
"Staples.f",
"CSE.f",
"S.T.E.P..f",
"Society_for_Industrial_and_Applied_Mathematics.f",
"Undergrads.f",
"Undergraduates.f",
"Christian_%27Eight-Ball%27_Alvarez.f",
]

#for elem in query1:
#    print(elem + " " + str(ranks[elem]))

for elem in query2:
    try: 
        print(elem + " " + str(ranks[elem]))
    except:
        print(elem + " MISSING")
